'use strict';

// Run with: node --test ~/.claude/scripts/tests/nexus-link.test.js

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawnSync } = require('child_process');

const SCRIPT = path.join(__dirname, '..', 'nexus-link.js');
const MARKER = 'GENERATED by Nexus';

function write(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function makeFixture() {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), 'nexus-link-test-'));
  const dirs = {
    base,
    root: path.join(base, 'nexus'),
    shared: path.join(base, 'agents-home', 'skills'),
    codex: path.join(base, 'codex', 'agents'),
    gemini: path.join(base, 'gemini', 'agents'),
    backup: path.join(base, 'backup'),
    config: path.join(base, 'config.json'),
  };
  const { root, shared, codex } = dirs;
  write(path.join(root, 'skills/alpha/SKILL.md'), '---\nname: alpha\ndescription: Alpha.\n---\nAlpha body\n');
  write(path.join(root, 'skills/beta/SKILL.md'), '---\nname: beta\ndescription: Beta.\n---\nBeta body (current)\n');
  write(path.join(root, 'skills/notaskill/README.md'), 'no SKILL.md here');
  write(path.join(root, 'agents/rev.md'),
    '---\nname: rev\ndescription: Reviews "code".\ntools: ["Read", "Grep"]\nmodel: opus\n---\n'
    + 'Check C:\\path and quotes """ inside.\n');
  write(path.join(root, 'agents/builder.md'),
    '---\nname: builder\ndescription: Builds.\ntools: ["Read", "Edit", "Bash"]\n---\nBuild it.\n');
  write(path.join(root, 'agents/sub/rev.md'), '---\nname: rev\ndescription: Duplicate.\n---\nDup.\n');
  write(path.join(shared, 'beta/SKILL.md'), '---\nname: beta\ndescription: Beta.\n---\nOLD COPY\n');
  write(path.join(shared, 'old-copy/SKILL.md'), '---\nname: old-copy\ndescription: Stale.\n---\nstale\n');
  write(path.join(shared, '.DS_Store'), 'junk');
  write(path.join(codex, 'x.toml'), 'name = "x"\n');
  write(path.join(codex, 'rev.toml'), 'name = "rev"\ndescription = "hand copy"\n');
  fs.mkdirSync(dirs.gemini, { recursive: true });
  return dirs;
}

function run(dirs, ...args) {
  return spawnSync('node', [SCRIPT, ...args], {
    env: {
      ...process.env,
      NEXUS_HOME: dirs.root,
      NEXUS_SHARED_SKILLS_DIR: dirs.shared,
      NEXUS_CODEX_AGENTS_DIR: dirs.codex,
      NEXUS_GEMINI_AGENTS_DIR: dirs.gemini,
      NEXUS_BACKUP_DIR: dirs.backup,
      NEXUS_LOCAL_CONFIG: dirs.config,
    },
    encoding: 'utf8',
  });
}

const isLinkTo = (entry, target) =>
  fs.lstatSync(entry).isSymbolicLink() && fs.realpathSync(entry) === fs.realpathSync(target);

function parseToml(file) {
  const py = 'import sys, tomllib, json; print(json.dumps(tomllib.load(open(sys.argv[1], "rb"))))';
  const r = spawnSync('python3', ['-c', py, file], { encoding: 'utf8' });
  assert.equal(r.status, 0, `TOML failed to parse: ${r.stderr}`);
  return JSON.parse(r.stdout);
}

test('default run links new skills and renders agents without touching unmanaged copies', () => {
  const d = makeFixture();
  const r = run(d);
  assert.equal(r.status, 0, r.stderr);

  assert.ok(isLinkTo(path.join(d.shared, 'alpha'), path.join(d.root, 'skills/alpha')));
  assert.ok(!fs.lstatSync(path.join(d.shared, 'beta')).isSymbolicLink(), 'copy left alone');
  assert.ok(fs.existsSync(path.join(d.shared, 'old-copy')), 'orphan copy left alone');
  assert.ok(!fs.existsSync(path.join(d.shared, 'notaskill')), 'dirs without SKILL.md are not skills');

  assert.match(fs.readFileSync(path.join(d.codex, 'builder.toml'), 'utf8'), new RegExp(MARKER));
  assert.equal(fs.readFileSync(path.join(d.codex, 'rev.toml'), 'utf8'), 'name = "rev"\ndescription = "hand copy"\n');
  assert.equal(fs.readFileSync(path.join(d.codex, 'x.toml'), 'utf8'), 'name = "x"\n');
  assert.ok(fs.existsSync(path.join(d.gemini, 'rev.md')));

  assert.match(r.stdout, /beta/);
  assert.match(r.stdout, /--replace-copies/);
  assert.match(r.stdout, /duplicate/i);
});

test('rendered Codex agent is valid TOML with the body verbatim plus a portability preamble', () => {
  const d = makeFixture();
  run(d, '--replace-copies');
  const toml = parseToml(path.join(d.codex, 'rev.toml'));
  assert.equal(toml.name, 'rev');
  assert.equal(toml.description, 'Reviews "code".');
  assert.ok(toml.developer_instructions.includes('Check C:\\path and quotes """ inside.'));
  assert.match(toml.developer_instructions, /read-only/i, 'tools without Edit/Write/Bash => read-only note');
  assert.doesNotMatch(parseToml(path.join(d.codex, 'builder.toml')).developer_instructions, /read-only/i);
});

test('rendered Gemini agent frontmatter has only keys Gemini accepts', () => {
  const d = makeFixture();
  run(d);
  const text = fs.readFileSync(path.join(d.gemini, 'rev.md'), 'utf8');
  const fm = text.match(/^---\n([\s\S]*?)\n---\n/)[1];
  const keys = fm.split('\n').map((l) => l.split(':')[0]);
  assert.deepEqual(keys, ['name', 'description']);
  assert.match(text, new RegExp(MARKER));
  assert.match(text, /read-only/i);
});

test('second run is a no-op and prints nothing with --quiet', () => {
  const d = makeFixture();
  run(d);
  const again = run(d, '--quiet');
  assert.equal(again.status, 0, again.stderr);
  assert.equal(again.stdout.trim(), '');
});

test('--replace-copies replaces only same-name copies; unrelated skills and agents stay put', () => {
  const d = makeFixture();
  const r = run(d, '--replace-copies');
  assert.equal(r.status, 0, r.stderr);
  assert.ok(isLinkTo(path.join(d.shared, 'beta'), path.join(d.root, 'skills/beta')));
  assert.ok(fs.existsSync(path.join(d.shared, 'old-copy/SKILL.md')), "someone's own skill is not touched");
  assert.match(fs.readFileSync(path.join(d.codex, 'rev.toml'), 'utf8'), new RegExp(MARKER));
  assert.equal(fs.readFileSync(path.join(d.codex, 'x.toml'), 'utf8'), 'name = "x"\n', "someone's own agent is not touched");

  const marker = JSON.parse(fs.readFileSync(path.join(d.shared, '.nexus-managed'), 'utf8'));
  assert.deepEqual(marker.ignore, ['old-copy'], 'pre-existing folders are remembered so they are never adopted');

  const backups = fs.readdirSync(d.backup, { recursive: true }).map(String);
  assert.ok(backups.some((p) => p.endsWith(path.join('beta', 'SKILL.md'))));
  assert.ok(backups.some((p) => p.endsWith('rev.toml')));
  assert.ok(!backups.some((p) => p.endsWith('old-copy') || p.endsWith('x.toml')));
});

test('--retire-unrelated is the explicit way to back up unrelated folders and agent files', () => {
  const d = makeFixture();
  const r = run(d, '--replace-copies', '--retire-unrelated');
  assert.equal(r.status, 0, r.stderr);
  assert.ok(!fs.existsSync(path.join(d.shared, 'old-copy')));
  assert.ok(!fs.existsSync(path.join(d.codex, 'x.toml')));
  const backups = fs.readdirSync(d.backup, { recursive: true }).map(String);
  assert.ok(backups.some((p) => p.endsWith('old-copy')));
  assert.ok(backups.some((p) => p.endsWith('x.toml')));
});

test('once managed, only skills created afterwards in another tool are adopted into Nexus', () => {
  const d = makeFixture();
  run(d, '--replace-copies');
  write(path.join(d.shared, 'fresh/SKILL.md'), '---\nname: fresh\ndescription: Made in Codex.\n---\nUse AskUserQuestion.\n');
  const r = run(d);
  assert.equal(r.status, 0, r.stderr);
  assert.ok(fs.existsSync(path.join(d.root, 'skills/fresh/SKILL.md')), 'moved into Nexus');
  assert.ok(isLinkTo(path.join(d.shared, 'fresh'), path.join(d.root, 'skills/fresh')));
  assert.match(r.stdout, /adopted/i);
  assert.match(r.stdout, /AskUserQuestion|portability/i, 'adopted skill is linted');
  assert.ok(!fs.existsSync(path.join(d.root, 'skills/old-copy')), 'pre-existing folder not adopted');
  assert.ok(fs.existsSync(path.join(d.shared, 'old-copy/SKILL.md')));
});

test('non-quiet notices tell same-name copies apart from unrelated folders', () => {
  const d = makeFixture();
  const r = run(d);
  assert.match(r.stdout, /same name as a Nexus skill[^\n]*beta/i);
  assert.match(r.stdout, /not from Nexus[^\n]*old-copy/i);
  assert.doesNotMatch(r.stdout, /real copies/i);
});

test('shareWith [] removes only what Nexus shared; shareWith ["codex"] skips Gemini', () => {
  const d = makeFixture();
  run(d);
  fs.writeFileSync(d.config, JSON.stringify({ shareWith: [] }));
  const off = run(d);
  assert.equal(off.status, 0, off.stderr);
  assert.ok(!fs.existsSync(path.join(d.shared, 'alpha')), 'our link removed');
  assert.ok(fs.existsSync(path.join(d.shared, 'beta/SKILL.md')), 'copy untouched');
  assert.ok(!fs.existsSync(path.join(d.codex, 'builder.toml')), 'generated agent removed');
  assert.ok(fs.existsSync(path.join(d.codex, 'x.toml')), 'unrelated agent untouched');
  assert.deepEqual(fs.readdirSync(d.gemini), []);

  fs.writeFileSync(d.config, JSON.stringify({ shareWith: ['codex'] }));
  run(d);
  assert.ok(isLinkTo(path.join(d.shared, 'alpha'), path.join(d.root, 'skills/alpha')));
  assert.ok(fs.existsSync(path.join(d.codex, 'builder.toml')));
  assert.deepEqual(fs.readdirSync(d.gemini), []);
});

test('deleting a source removes only the links and files Nexus generated', () => {
  const d = makeFixture();
  run(d, '--replace-copies');
  fs.rmSync(path.join(d.root, 'skills/alpha'), { recursive: true });
  fs.rmSync(path.join(d.root, 'agents/builder.md'));
  fs.symlinkSync(os.tmpdir(), path.join(d.shared, 'foreign'));
  const r = run(d);
  assert.equal(r.status, 0, r.stderr);
  assert.ok(!fs.existsSync(path.join(d.shared, 'alpha')));
  assert.ok(!fs.existsSync(path.join(d.codex, 'builder.toml')));
  assert.ok(!fs.existsSync(path.join(d.gemini, 'builder.md')));
  assert.ok(fs.lstatSync(path.join(d.shared, 'foreign')).isSymbolicLink(), 'foreign link untouched');
});

test('links made through an old path (e.g. ~/.claude before the move) are re-pointed or cleaned up', () => {
  const d = makeFixture();
  const alias = path.join(d.base, 'old-home');
  fs.symlinkSync(d.root, alias); // like ~/.claude/skills -> ~/.nexus/skills after the move
  fs.symlinkSync(path.join(alias, 'skills/alpha'), path.join(d.shared, 'alpha'));
  fs.symlinkSync(path.join(alias, 'skills/gone'), path.join(d.shared, 'gone'));
  const r = run(d);
  assert.equal(r.status, 0, r.stderr);
  assert.equal(fs.readlinkSync(path.join(d.shared, 'alpha')), path.join(d.root, 'skills/alpha'), 're-pointed to the canonical path');
  assert.equal(fs.readdirSync(d.shared).includes('gone'), false, 'dangling old-path link removed');
});

test('refuses to run against a Nexus root with no skills/ or agents/ folder (never mass-removes)', () => {
  const d = makeFixture();
  run(d);
  fs.renameSync(path.join(d.root, 'agents'), path.join(d.base, 'agents-away'));
  const r = run(d);
  assert.equal(r.status, 1);
  assert.match(r.stderr, /agents/);
  assert.ok(fs.existsSync(path.join(d.codex, 'builder.toml')), 'generated agents untouched');
  assert.ok(fs.existsSync(path.join(d.shared, 'alpha')), 'skill links untouched');
});

test('a tool that is not installed (parent dir missing) is skipped cleanly', () => {
  const d = makeFixture();
  const r = spawnSync('node', [SCRIPT], {
    env: {
      ...process.env,
      NEXUS_HOME: d.root,
      NEXUS_SHARED_SKILLS_DIR: d.shared,
      NEXUS_CODEX_AGENTS_DIR: path.join(d.base, 'no-codex-here', 'agents'),
      NEXUS_GEMINI_AGENTS_DIR: d.gemini,
      NEXUS_BACKUP_DIR: d.backup,
      NEXUS_LOCAL_CONFIG: d.config,
    },
    encoding: 'utf8',
  });
  assert.equal(r.status, 0, r.stderr);
  assert.ok(!fs.existsSync(path.join(d.base, 'no-codex-here')));
});
