#!/usr/bin/env node
'use strict';

/**
 * nexus-link.js
 *
 * Makes every Nexus skill and agent available to the other AI coding tools on
 * this machine, with no copies to drift:
 *   skills -> one symlink per skill in the shared skills dir (~/.agents/skills),
 *             which Codex and Gemini CLI both read
 *   agents -> rendered into each tool's own format (Codex .toml, Gemini .md),
 *             marked GENERATED, with a short tool-neutral preamble
 *
 * Ownership: only symlinks pointing into Nexus's skills dir and files carrying
 * the GENERATED marker are ever replaced or removed. Anything else is reported
 * and left alone, unless --replace-copies (which backs it up first). After a
 * --replace-copies run the shared skills dir is marked managed; from then on a
 * real skill folder that appears there (made by another tool) is adopted:
 * moved into Nexus and linked back.
 *
 * Usage: node nexus-link.js [--replace-copies] [--quiet]
 *   --quiet prints only when something changed (used by the Stop hook).
 * Env overrides (tests): NEXUS_HOME, NEXUS_SHARED_SKILLS_DIR,
 *   NEXUS_CODEX_AGENTS_DIR, NEXUS_GEMINI_AGENTS_DIR, NEXUS_BACKUP_DIR
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { parseFrontmatter } = require('./generate-inventory.js');
const { lintFile } = require('./lib/portability');

const HOME = os.homedir();
const env = process.env;
const ROOT = path.resolve(env.NEXUS_HOME || env.CLAUDE_HOME || path.join(HOME, '.claude'));
const SKILLS_DIR = path.join(ROOT, 'skills');
const SHARED_SKILLS = path.resolve(env.NEXUS_SHARED_SKILLS_DIR || path.join(HOME, '.agents', 'skills'));
const CODEX_AGENTS = path.resolve(env.NEXUS_CODEX_AGENTS_DIR || path.join(env.CODEX_HOME || path.join(HOME, '.codex'), 'agents'));
const GEMINI_AGENTS = path.resolve(env.NEXUS_GEMINI_AGENTS_DIR || path.join(HOME, '.gemini', 'agents'));
const BACKUP_BASE = path.resolve(env.NEXUS_BACKUP_DIR || path.join(ROOT, 'backups'));

const MARKER = 'GENERATED by Nexus';
const MANAGED_FILE = '.nexus-managed';
const NAME_PATTERN = /^[a-z0-9-_]+$/;
const MAX_LISTED = 8;

const PORTABILITY_NOTE = 'This agent is shared across AI coding tools. Where it names a specific tool, '
  + 'use your equivalent: Read -> read a file; Grep/Glob -> search the codebase; Bash -> run a shell '
  + 'command; Edit/Write -> change or create files; WebFetch/WebSearch -> fetch a page / search the web; '
  + 'Agent/Task -> hand off to another agent if you can, otherwise do the work yourself; '
  + 'AskUserQuestion -> ask the user; TodoWrite -> keep a task list.';
const READ_ONLY_NOTE = 'Scope: read-only. Investigate and report back; do not create, modify, or delete files.';

const tilde = (p) => (p.startsWith(HOME) ? `~${p.slice(HOME.length)}` : p);

// ---------- filesystem helpers ----------

function lstatOrNull(p) {
  try { return fs.lstatSync(p); } catch { return null; }
}

function isOurLink(entry) {
  const target = path.resolve(path.dirname(entry), fs.readlinkSync(entry));
  let realSkills = SKILLS_DIR;
  try { realSkills = fs.realpathSync(SKILLS_DIR); } catch { /* keep unresolved */ }
  return [SKILLS_DIR, realSkills].some((dir) => target.startsWith(dir + path.sep));
}

function sameTarget(entry, dir) {
  try { return fs.realpathSync(entry) === fs.realpathSync(dir); } catch { return false; }
}

function move(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  try {
    fs.renameSync(src, dest);
  } catch (err) {
    if (err.code !== 'EXDEV') throw err;
    fs.cpSync(src, dest, { recursive: true });
    fs.rmSync(src, { recursive: true, force: true });
  }
}

function makeBackup() {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const dir = path.join(BACKUP_BASE, `nexus-link-${stamp}`);
  return (src, label) => move(src, path.join(dir, label, path.basename(src)));
}

// ---------- skills ----------

function collectSkills() {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  return fs.readdirSync(SKILLS_DIR)
    .filter((name) => !name.startsWith('.') && fs.existsSync(path.join(SKILLS_DIR, name, 'SKILL.md')))
    .map((name) => ({ name, dir: path.join(SKILLS_DIR, name) }));
}

function linkSkill(skill, ctx) {
  const entry = path.join(SHARED_SKILLS, skill.name);
  const st = lstatOrNull(entry);
  if (!st) {
    fs.symlinkSync(skill.dir, entry, 'dir');
    return ctx.out.linked.push(skill.name);
  }
  if (st.isSymbolicLink()) {
    if (sameTarget(entry, skill.dir) || !isOurLink(entry)) return undefined;
    fs.unlinkSync(entry);
    fs.symlinkSync(skill.dir, entry, 'dir');
    return ctx.out.linked.push(skill.name);
  }
  if (!st.isDirectory()) return undefined;
  if (!ctx.replaceCopies) return ctx.out.copies.push(skill.name);
  ctx.backup(entry, 'agents-skills');
  fs.symlinkSync(skill.dir, entry, 'dir');
  return ctx.out.replaced.push(skill.name);
}

function adoptSkill(name, entry, ctx) {
  const dest = path.join(SKILLS_DIR, name);
  move(entry, dest);
  fs.symlinkSync(dest, entry, 'dir');
  const errors = lintFile(path.join(dest, 'SKILL.md'), ROOT).findings.filter((f) => f.severity === 'error');
  ctx.out.adopted.push(errors.length
    ? `${name} (portability: ${errors.length} to fix, e.g. "${errors[0].match}"; run nexus-portability.js skills/${name}/SKILL.md)`
    : name);
}

function handleExtraSkill(name, ctx) {
  const entry = path.join(SHARED_SKILLS, name);
  const st = lstatOrNull(entry);
  if (!st) return;
  if (st.isSymbolicLink()) {
    if (isOurLink(entry)) { fs.unlinkSync(entry); ctx.out.unlinked.push(name); }
    return;
  }
  if (!st.isDirectory()) return;
  const isSkill = fs.existsSync(path.join(entry, 'SKILL.md'));
  if (ctx.managed && isSkill && !fs.existsSync(path.join(SKILLS_DIR, name))) {
    adoptSkill(name, entry, ctx);
  } else if (ctx.replaceCopies) {
    ctx.backup(entry, 'agents-skills');
    ctx.out.retired.push(name);
  } else {
    ctx.out.unmanaged.push(name);
  }
}

function syncSkills(ctx) {
  if (!fs.existsSync(path.dirname(SHARED_SKILLS))) return;
  fs.mkdirSync(SHARED_SKILLS, { recursive: true });
  const skills = collectSkills();
  const names = new Set(skills.map((s) => s.name));
  const skillCtx = { ...ctx, managed: fs.existsSync(path.join(SHARED_SKILLS, MANAGED_FILE)) };
  skills.forEach((skill) => linkSkill(skill, skillCtx));
  fs.readdirSync(SHARED_SKILLS)
    .filter((name) => !name.startsWith('.') && !names.has(name))
    .forEach((name) => handleExtraSkill(name, skillCtx));
  if (ctx.replaceCopies) fs.writeFileSync(path.join(SHARED_SKILLS, MANAGED_FILE), `${MARKER}: skills here are links into ${tilde(SKILLS_DIR)}\n`);
}

// ---------- agents ----------

function walkAgents(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith('.')) return [];
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walkAgents(full);
    return entry.name.endsWith('.md') ? [full] : [];
  });
}

function toAgent(file) {
  const { data, body } = parseFrontmatter(fs.readFileSync(file, 'utf8'));
  if (!data.name || !data.description) return null;
  const tools = data.tools || '';
  return {
    name: data.name,
    description: data.description,
    rel: path.relative(ROOT, file),
    body: body.replace(/\r\n/g, '\n').trim(),
    readOnly: tools !== '' && !/\b(Edit|Write|MultiEdit|NotebookEdit)\b/.test(tools),
  };
}

function collectAgents(out) {
  const depth = (f) => f.split(path.sep).length;
  const files = walkAgents(path.join(ROOT, 'agents')).sort((a, b) => depth(a) - depth(b) || a.localeCompare(b));
  const byName = new Map();
  for (const agent of files.map(toAgent).filter(Boolean)) {
    if (!NAME_PATTERN.test(agent.name)) { out.invalid.push(`${agent.name} (${agent.rel})`); continue; }
    if (byName.has(agent.name)) { out.duplicates.push(`${agent.name}: ${agent.rel} ignored, ${byName.get(agent.name).rel} used`); continue; }
    byName.set(agent.name, agent);
  }
  return [...byName.values()];
}

function instructions(agent) {
  const notes = agent.readOnly ? `${PORTABILITY_NOTE}\n\n${READ_ONLY_NOTE}` : PORTABILITY_NOTE;
  return `${notes}\n\n${agent.body}`;
}

function tomlMultiline(text) {
  const escaped = text
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '""\\"')
    .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`);
  return `"""\n${escaped}\n"""`;
}

function renderCodex(agent) {
  return `# ${MARKER} from ${agent.rel}. Edit that file instead; this one is rewritten automatically.\n`
    + `name = ${JSON.stringify(agent.name)}\n`
    + `description = ${JSON.stringify(agent.description)}\n`
    + `developer_instructions = ${tomlMultiline(instructions(agent))}\n`;
}

function renderGemini(agent) {
  return `---\nname: ${agent.name}\ndescription: ${JSON.stringify(agent.description)}\n---\n`
    + `<!-- ${MARKER} from ${agent.rel}. Edit that file instead; this one is rewritten automatically. -->\n\n`
    + `${instructions(agent)}\n`;
}

function writeAgentFile(file, content, stats, ctx, label) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (current === content) return;
  if (current === null || current.includes(MARKER)) {
    fs.writeFileSync(file, content);
    stats.written.push(path.basename(file));
  } else if (ctx.replaceCopies) {
    ctx.backup(file, label);
    fs.writeFileSync(file, content);
    stats.replaced.push(path.basename(file));
  } else {
    stats.copies.push(path.basename(file));
  }
}

function syncAgentTarget(agents, target, ctx) {
  const { dir, ext, render, label } = target;
  const stats = { label, written: [], replaced: [], removed: [], copies: [], unmanaged: [] };
  if (!fs.existsSync(path.dirname(dir))) return stats;
  fs.mkdirSync(dir, { recursive: true });
  const wanted = new Set(agents.map((a) => `${a.name}${ext}`));
  agents.forEach((agent) => writeAgentFile(path.join(dir, `${agent.name}${ext}`), render(agent), stats, ctx, label));
  for (const name of fs.readdirSync(dir).filter((n) => n.endsWith(ext) && !wanted.has(n))) {
    const file = path.join(dir, name);
    if (!fs.statSync(file).isFile()) continue;
    if (fs.readFileSync(file, 'utf8').includes(MARKER)) { fs.rmSync(file); stats.removed.push(name); }
    else if (ctx.replaceCopies) { ctx.backup(file, label); stats.removed.push(name); }
    else stats.unmanaged.push(name);
  }
  return stats;
}

// ---------- reporting ----------

function list(names) {
  const shown = names.slice(0, MAX_LISTED).join(', ');
  return names.length > MAX_LISTED ? `${shown} (+${names.length - MAX_LISTED} more)` : shown;
}

function changeLines(out, agentStats) {
  const lines = [];
  const add = (items, text) => { if (items.length) lines.push(`${text}: ${list(items)}`); };
  add(out.linked, `Linked ${out.linked.length} skill(s) into ${tilde(SHARED_SKILLS)}`);
  add(out.replaced, `Replaced ${out.replaced.length} old skill copy(ies) with links (backed up)`);
  add(out.retired, `Retired ${out.retired.length} stale skill copy(ies) (backed up)`);
  add(out.adopted, `Adopted ${out.adopted.length} skill(s) created in another tool into Nexus`);
  add(out.unlinked, `Removed ${out.unlinked.length} link(s) to deleted skills`);
  for (const s of agentStats) {
    add(s.written, `${s.label}: wrote ${s.written.length} agent(s)`);
    add(s.replaced, `${s.label}: replaced ${s.replaced.length} old agent copy(ies) (backed up)`);
    add(s.removed, `${s.label}: removed ${s.removed.length} agent file(s) no longer in Nexus`);
  }
  return lines;
}

function noticeLines(out, agentStats) {
  const lines = [];
  const copies = [...out.copies, ...out.unmanaged];
  if (copies.length) {
    lines.push(`${copies.length} skill folder(s) in ${tilde(SHARED_SKILLS)} are real copies, not links (left alone): ${list(copies)}.`
      + ' Run with --replace-copies to back them up and link Nexus instead.');
  }
  for (const s of agentStats) {
    const other = [...s.copies, ...s.unmanaged];
    if (other.length) lines.push(`${s.label}: ${other.length} agent file(s) not made by Nexus (left alone): ${list(other)}. --replace-copies backs them up.`);
  }
  if (out.duplicates.length) lines.push(`Duplicate agent names: ${out.duplicates.join('; ')}`);
  if (out.invalid.length) lines.push(`Agent names other tools reject (use lowercase-with-dashes): ${list(out.invalid)}`);
  return lines;
}

function main(argv) {
  const quiet = argv.includes('--quiet');
  const out = { linked: [], replaced: [], retired: [], adopted: [], unlinked: [], copies: [], unmanaged: [], duplicates: [], invalid: [] };
  const ctx = { replaceCopies: argv.includes('--replace-copies'), backup: makeBackup(), out };

  syncSkills(ctx);
  const agents = collectAgents(out);
  const agentStats = [
    { dir: CODEX_AGENTS, ext: '.toml', render: renderCodex, label: 'Codex' },
    { dir: GEMINI_AGENTS, ext: '.md', render: renderGemini, label: 'Gemini' },
  ].map((target) => syncAgentTarget(agents, target, ctx));

  const changes = changeLines(out, agentStats);
  const notices = quiet ? [] : noticeLines(out, agentStats);
  if (changes.length || notices.length) {
    console.log(['nexus-link:', ...changes, ...notices].join('\n  '));
  } else if (!quiet) {
    console.log('nexus-link: everything already in sync.');
  }
  return 0;
}

if (require.main === module) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (err) {
    console.error(`nexus-link: ${err.message}`);
    process.exitCode = 1;
  }
}

module.exports = { main, renderCodex, renderGemini };
