#!/usr/bin/env node
'use strict';

/**
 * nexus-link.js
 *
 * Makes every Nexus skill and agent available to the other AI coding tools on
 * this machine, with no copies to drift:
 *   skills -> one symlink per skill in the shared skills dir (~/.agents/skills),
 *             which Codex and Gemini CLI both read
 *   agents -> rendered into each tool's own format (Codex .toml, Gemini .md),
 *             marked GENERATED, with a short tool-neutral preamble
 *   instructions -> NEXUS.md (+ tool notes, rules, personal file) in a marked
 *             block of each tool's global instruction file (lib/nexus-instructions.js)
 * Which tools are set up comes from "tools" in ~/.nexus-local/config.json
 * (lib/nexus-config.js); no tool is special. Turning a tool off removes only
 * what Nexus put there.
 *
 * Ownership: only symlinks pointing into Nexus's skills dir and files carrying
 * the GENERATED marker are ever replaced or removed. Everything else is
 * reported and left alone, except:
 *   --replace-copies    back up folders/agent files that have the SAME NAME as
 *                       a Nexus skill/agent and replace them with Nexus's version.
 *                       Also marks the shared skills dir managed: skills created
 *                       there afterwards by another tool are adopted into Nexus
 *                       (folders already present are remembered and never adopted).
 *   --retire-unrelated  also back up folders/agent files that are NOT from Nexus.
 *                       Only for stale leftovers; never needed on a fresh install.
 *
 * Usage: node nexus-link.js [--replace-copies] [--retire-unrelated] [--quiet]
 *   --quiet prints only when something changed (used by the Stop hook).
 * Env overrides (tests): NEXUS_HOME, NEXUS_SHARED_SKILLS_DIR, NEXUS_CODEX_AGENTS_DIR,
 *   NEXUS_GEMINI_AGENTS_DIR, NEXUS_BACKUP_DIR, NEXUS_LOCAL_CONFIG, NEXUS_CLAUDE_INSTRUCTIONS,
 *   NEXUS_CODEX_INSTRUCTIONS, NEXUS_GEMINI_INSTRUCTIONS, NEXUS_LOCAL_INSTRUCTIONS
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { parseFrontmatter } = require('./generate-inventory.js');
const { lintFile } = require('./lib/portability');
const { loadConfig, configPath } = require('./lib/nexus-config');
const { syncInstructions } = require('./lib/nexus-instructions');

const HOME = os.homedir();
const env = process.env;
const ROOT = require('./lib/nexus-home').nexusHome();
const SKILLS_DIR = path.join(ROOT, 'skills');
const SHARED_SKILLS = path.resolve(env.NEXUS_SHARED_SKILLS_DIR || path.join(HOME, '.agents', 'skills'));
const CODEX_AGENTS = path.resolve(env.NEXUS_CODEX_AGENTS_DIR || path.join(env.CODEX_HOME || path.join(HOME, '.codex'), 'agents'));
const GEMINI_AGENTS = path.resolve(env.NEXUS_GEMINI_AGENTS_DIR || path.join(HOME, '.gemini', 'agents'));
const BACKUP_BASE = path.resolve(env.NEXUS_BACKUP_DIR || path.join(ROOT, 'backups'));
const CODEX_HOME = env.CODEX_HOME || path.join(HOME, '.codex');
const INSTRUCTION_TARGETS = [
  { tool: 'claude', label: 'Claude', file: env.NEXUS_CLAUDE_INSTRUCTIONS || path.join(HOME, '.claude', 'CLAUDE.md') },
  { tool: 'codex', label: 'Codex', file: env.NEXUS_CODEX_INSTRUCTIONS || path.join(CODEX_HOME, 'AGENTS.md') },
  { tool: 'gemini', label: 'Gemini', file: env.NEXUS_GEMINI_INSTRUCTIONS || path.join(HOME, '.gemini', 'GEMINI.md') },
];
const LOCAL_INSTRUCTIONS = env.NEXUS_LOCAL_INSTRUCTIONS || path.join(path.dirname(configPath()), 'instructions.md');

const MARKER = 'GENERATED by Nexus';
const MANAGED_FILE = '.nexus-managed';
const NAME_PATTERN = /^[a-z0-9-_]+$/;
const MAX_LISTED = 8;

const PORTABILITY_NOTE = 'This agent is shared across AI coding tools. Where it names a specific tool, '
  + 'use your equivalent: Read -> read a file; Grep/Glob -> search the codebase; Bash -> run a shell '
  + 'command; Edit/Write -> change or create files; WebFetch/WebSearch -> fetch a page / search the web; '
  + 'Agent/Task -> hand off to another agent if you can, otherwise do the work yourself; '
  + 'AskUserQuestion -> ask the user; TodoWrite -> keep a task list.';
const READ_ONLY_NOTE = 'Scope: read-only. Investigate and report back; do not create, modify, or delete files.';

const tilde = (p) => (p.startsWith(HOME) ? `~${p.slice(HOME.length)}` : p);

// ---------- filesystem helpers ----------

function lstatOrNull(p) {
  try { return fs.lstatSync(p); } catch { return null; }
}

function realOrSelf(p) {
  try { return fs.realpathSync(p); } catch { return p; }
}

/** True if the link points into Nexus's skills dir, directly or through an old path (e.g. ~/.claude/skills). */
function isOurLink(entry) {
  const target = path.resolve(path.dirname(entry), fs.readlinkSync(entry));
  const skillDirs = [SKILLS_DIR, realOrSelf(SKILLS_DIR)];
  const viaRealParent = path.join(realOrSelf(path.dirname(target)), path.basename(target));
  return [target, viaRealParent].some((t) => skillDirs.some((dir) => t.startsWith(dir + path.sep)));
}

function sameTarget(entry, dir) {
  try { return fs.realpathSync(entry) === fs.realpathSync(dir); } catch { return false; }
}

function move(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  try {
    fs.renameSync(src, dest);
  } catch (err) {
    if (err.code !== 'EXDEV') throw err;
    fs.cpSync(src, dest, { recursive: true });
    fs.rmSync(src, { recursive: true, force: true });
  }
}

function makeBackup() {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const dir = path.join(BACKUP_BASE, `nexus-link-${stamp}`);
  return (src, label) => move(src, path.join(dir, label, path.basename(src)));
}

// ---------- managed marker ----------

function readMarker() {
  const file = path.join(SHARED_SKILLS, MANAGED_FILE);
  if (!fs.existsSync(file)) return null;
  try {
    const data = JSON.parse(fs.readFileSync(file, 'utf8'));
    return { managedSince: data.managedSince || null, ignore: Array.isArray(data.ignore) ? data.ignore : [] };
  } catch {
    return { managedSince: null, ignore: [] }; // older plain-text marker
  }
}

function writeMarker(previous, unrelated) {
  const data = {
    note: `${MARKER}: skills here are links into ${tilde(SKILLS_DIR)}. "ignore" lists folders that were here before and are never adopted.`,
    managedSince: (previous && previous.managedSince) || new Date().toISOString(),
    ignore: [...new Set([...((previous && previous.ignore) || []), ...unrelated])].sort(),
  };
  fs.writeFileSync(path.join(SHARED_SKILLS, MANAGED_FILE), `${JSON.stringify(data, null, 2)}\n`);
}

// ---------- skills ----------

function collectSkills() {
  if (!fs.existsSync(SKILLS_DIR)) return [];
  return fs.readdirSync(SKILLS_DIR)
    .filter((name) => !name.startsWith('.') && fs.existsSync(path.join(SKILLS_DIR, name, 'SKILL.md')))
    .map((name) => ({ name, dir: path.join(SKILLS_DIR, name) }));
}

function linkSkill(skill, ctx) {
  const entry = path.join(SHARED_SKILLS, skill.name);
  const st = lstatOrNull(entry);
  if (!st) {
    fs.symlinkSync(skill.dir, entry, 'dir');
    return ctx.out.linked.push(skill.name);
  }
  if (st.isSymbolicLink()) {
    const pointsHere = sameTarget(entry, skill.dir);
    if (!pointsHere && !isOurLink(entry)) return undefined;
    if (fs.readlinkSync(entry) === skill.dir) return undefined;
    fs.unlinkSync(entry);
    fs.symlinkSync(skill.dir, entry, 'dir');
    return (pointsHere ? ctx.out.repointed : ctx.out.linked).push(skill.name);
  }
  if (!st.isDirectory()) return undefined;
  if (!ctx.replaceCopies) return ctx.out.copies.push(skill.name);
  ctx.backup(entry, 'agents-skills');
  fs.symlinkSync(skill.dir, entry, 'dir');
  return ctx.out.replaced.push(skill.name);
}

function adoptSkill(name, entry, ctx) {
  const dest = path.join(SKILLS_DIR, name);
  move(entry, dest);
  fs.symlinkSync(dest, entry, 'dir');
  const errors = lintFile(path.join(dest, 'SKILL.md'), ROOT).findings.filter((f) => f.severity === 'error');
  ctx.out.adopted.push(errors.length
    ? `${name} (portability: ${errors.length} to fix, e.g. "${errors[0].match}"; run nexus-portability.js skills/${name}/SKILL.md)`
    : name);
}

function handleExtraSkill(name, ctx) {
  const entry = path.join(SHARED_SKILLS, name);
  const st = lstatOrNull(entry);
  if (!st) return;
  if (st.isSymbolicLink()) {
    if (isOurLink(entry)) { fs.unlinkSync(entry); ctx.out.unlinked.push(name); }
    return;
  }
  if (!st.isDirectory() || ctx.disabled) return;
  const adoptable = ctx.marker && !ctx.marker.ignore.includes(name)
    && fs.existsSync(path.join(entry, 'SKILL.md')) && !fs.existsSync(path.join(SKILLS_DIR, name));
  if (adoptable) {
    adoptSkill(name, entry, ctx);
  } else if (ctx.retireUnrelated) {
    ctx.backup(entry, 'agents-skills');
    ctx.out.retired.push(name);
  } else {
    ctx.out.unmanaged.push(name);
  }
}

function syncSkills(ctx, enabled) {
  if (!enabled && !fs.existsSync(SHARED_SKILLS)) return;
  fs.mkdirSync(SHARED_SKILLS, { recursive: true });
  const skills = enabled ? collectSkills() : [];
  const names = new Set(skills.map((s) => s.name));
  const skillCtx = { ...ctx, disabled: !enabled, marker: readMarker() };
  skills.forEach((skill) => linkSkill(skill, skillCtx));
  fs.readdirSync(SHARED_SKILLS)
    .filter((name) => !name.startsWith('.') && !names.has(name))
    .forEach((name) => handleExtraSkill(name, skillCtx));
  if (enabled && ctx.replaceCopies) writeMarker(skillCtx.marker, ctx.out.unmanaged);
}

// ---------- agents ----------

function walkAgents(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    if (entry.name.startsWith('.')) return [];
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walkAgents(full);
    return entry.name.endsWith('.md') ? [full] : [];
  });
}

function toAgent(file) {
  const { data, body } = parseFrontmatter(fs.readFileSync(file, 'utf8'));
  if (!data.name || !data.description) return null;
  const tools = data.tools || '';
  return {
    name: data.name,
    description: data.description,
    rel: path.relative(ROOT, file),
    body: body.replace(/\r\n/g, '\n').trim(),
    readOnly: tools !== '' && !/\b(Edit|Write|MultiEdit|NotebookEdit)\b/.test(tools),
  };
}

function collectAgents(out) {
  const depth = (f) => f.split(path.sep).length;
  const files = walkAgents(path.join(ROOT, 'agents')).sort((a, b) => depth(a) - depth(b) || a.localeCompare(b));
  const byName = new Map();
  for (const agent of files.map(toAgent).filter(Boolean)) {
    if (!NAME_PATTERN.test(agent.name)) { out.invalid.push(`${agent.name} (${agent.rel})`); continue; }
    if (byName.has(agent.name)) { out.duplicates.push(`${agent.name}: ${agent.rel} ignored, ${byName.get(agent.name).rel} used`); continue; }
    byName.set(agent.name, agent);
  }
  return [...byName.values()];
}

function instructions(agent) {
  const notes = agent.readOnly ? `${PORTABILITY_NOTE}\n\n${READ_ONLY_NOTE}` : PORTABILITY_NOTE;
  return `${notes}\n\n${agent.body}`;
}

function tomlMultiline(text) {
  const escaped = text
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '""\\"')
    .replace(/[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`);
  return `"""\n${escaped}\n"""`;
}

function renderCodex(agent) {
  return `# ${MARKER} from ${agent.rel}. Edit that file instead; this one is rewritten automatically.\n`
    + `name = ${JSON.stringify(agent.name)}\n`
    + `description = ${JSON.stringify(agent.description)}\n`
    + `developer_instructions = ${tomlMultiline(instructions(agent))}\n`;
}

function renderGemini(agent) {
  return `---\nname: ${agent.name}\ndescription: ${JSON.stringify(agent.description)}\n---\n`
    + `<!-- ${MARKER} from ${agent.rel}. Edit that file instead; this one is rewritten automatically. -->\n\n`
    + `${instructions(agent)}\n`;
}

function writeAgentFile(file, content, stats, ctx, label) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (current === content) return;
  if (current === null || current.includes(MARKER)) {
    fs.writeFileSync(file, content);
    stats.written.push(path.basename(file));
  } else if (ctx.replaceCopies) {
    ctx.backup(file, label);
    fs.writeFileSync(file, content);
    stats.replaced.push(path.basename(file));
  } else {
    stats.copies.push(path.basename(file));
  }
}

function handleExtraAgentFile(file, stats, ctx, label, enabled) {
  const name = path.basename(file);
  if (fs.readFileSync(file, 'utf8').includes(MARKER)) { fs.rmSync(file); stats.removed.push(name); }
  else if (!enabled) return;
  else if (ctx.retireUnrelated) { ctx.backup(file, label); stats.retired.push(name); }
  else stats.unmanaged.push(name);
}

function syncAgentTarget(agents, target, ctx) {
  const { dir, ext, render, label, enabled } = target;
  const stats = { label, written: [], replaced: [], removed: [], retired: [], copies: [], unmanaged: [] };
  if (!fs.existsSync(path.dirname(dir)) || (!enabled && !fs.existsSync(dir))) return stats;
  fs.mkdirSync(dir, { recursive: true });
  const shared = enabled ? agents : [];
  const wanted = new Set(shared.map((a) => `${a.name}${ext}`));
  shared.forEach((agent) => writeAgentFile(path.join(dir, `${agent.name}${ext}`), render(agent), stats, ctx, label));
  for (const name of fs.readdirSync(dir).filter((n) => n.endsWith(ext) && !wanted.has(n))) {
    const file = path.join(dir, name);
    if (fs.statSync(file).isFile()) handleExtraAgentFile(file, stats, ctx, label, enabled);
  }
  return stats;
}

// ---------- reporting ----------

function list(names) {
  const shown = names.slice(0, MAX_LISTED).join(', ');
  return names.length > MAX_LISTED ? `${shown} (+${names.length - MAX_LISTED} more)` : shown;
}

function changeLines(out, agentStats, instructions) {
  const lines = [];
  const add = (items, text) => { if (items.length) lines.push(`${text}: ${list(items)}`); };
  add(out.linked, `Linked ${out.linked.length} skill(s) into ${tilde(SHARED_SKILLS)}`);
  add(out.repointed, `Re-pointed ${out.repointed.length} skill link(s) to ${tilde(SKILLS_DIR)}`);
  add(out.replaced, `Replaced ${out.replaced.length} same-name skill copy(ies) with links (backed up)`);
  add(out.retired, `Retired ${out.retired.length} unrelated skill folder(s) (backed up)`);
  add(out.adopted, `Adopted ${out.adopted.length} skill(s) created in another tool into Nexus`);
  add(out.unlinked, `Removed ${out.unlinked.length} Nexus skill link(s)`);
  for (const s of agentStats) {
    add(s.written, `${s.label}: wrote ${s.written.length} agent(s)`);
    add(s.replaced, `${s.label}: replaced ${s.replaced.length} same-name agent copy(ies) (backed up)`);
    add(s.removed, `${s.label}: removed ${s.removed.length} Nexus agent file(s)`);
    add(s.retired, `${s.label}: retired ${s.retired.length} unrelated agent file(s) (backed up)`);
  }
  const verbs = {
    written: (f) => `updated the Nexus block in ${f}`,
    replaced: (f) => `replaced ${f} with the Nexus block (old file backed up)`,
    removed: (f) => `removed the Nexus block from ${f}`,
  };
  for (const { label, file, action } of instructions) {
    if (verbs[action]) lines.push(`${label}: ${verbs[action](tilde(file))}`);
  }
  return lines;
}

function noticeLines(out, agentStats, instructions) {
  const lines = instructions.filter((i) => i.action === 'skipped-link')
    .map((i) => `${i.label}: ${tilde(i.file)} is a link to somewhere else, so the Nexus block was not added.`);
  const where = tilde(SHARED_SKILLS);
  if (out.copies.length) {
    lines.push(`${out.copies.length} folder(s) in ${where} have the same name as a Nexus skill but are separate copies (left alone): ${list(out.copies)}.`
      + ' Run with --replace-copies to back them up and link Nexus instead.');
  }
  if (out.unmanaged.length) lines.push(`${out.unmanaged.length} other skill folder(s) in ${where} are not from Nexus (left alone): ${list(out.unmanaged)}.`);
  for (const s of agentStats) {
    if (s.copies.length) {
      lines.push(`${s.label}: ${s.copies.length} agent file(s) have the same name as a Nexus agent but weren't made by Nexus (left alone): ${list(s.copies)}.`
        + ' --replace-copies backs them up and regenerates them.');
    }
    if (s.unmanaged.length) lines.push(`${s.label}: ${s.unmanaged.length} agent file(s) are not from Nexus (left alone): ${list(s.unmanaged)}.`);
  }
  if (out.duplicates.length) lines.push(`Duplicate agent names: ${out.duplicates.join('; ')}`);
  if (out.invalid.length) lines.push(`Agent names other tools reject (use lowercase-with-dashes): ${list(out.invalid)}`);
  return lines;
}

function assertCompleteRoot() {
  for (const dir of [SKILLS_DIR, path.join(ROOT, 'agents')]) {
    if (!fs.existsSync(dir)) {
      throw new Error(`${tilde(dir)} not found; refusing to sync from an incomplete Nexus root, so nothing shared gets removed`);
    }
  }
}

function main(argv) {
  assertCompleteRoot();
  const quiet = argv.includes('--quiet');
  const { tools } = loadConfig();
  const out = { linked: [], repointed: [], replaced: [], retired: [], adopted: [], unlinked: [], copies: [], unmanaged: [], duplicates: [], invalid: [] };
  const ctx = {
    replaceCopies: argv.includes('--replace-copies'),
    retireUnrelated: argv.includes('--retire-unrelated'),
    backup: makeBackup(),
    out,
  };

  syncSkills(ctx, tools.includes('codex') || tools.includes('gemini'));
  const agents = collectAgents(out);
  const agentStats = [
    { dir: CODEX_AGENTS, ext: '.toml', render: renderCodex, label: 'Codex', enabled: tools.includes('codex') },
    { dir: GEMINI_AGENTS, ext: '.md', render: renderGemini, label: 'Gemini', enabled: tools.includes('gemini') },
  ].map((target) => syncAgentTarget(agents, target, ctx));
  const instructions = syncInstructions({
    tools,
    root: ROOT,
    targets: INSTRUCTION_TARGETS,
    localFile: LOCAL_INSTRUCTIONS,
    replaceCopies: ctx.replaceCopies,
    backup: (file) => ctx.backup(file, 'instructions'),
  });

  const changes = changeLines(out, agentStats, instructions);
  const notices = quiet ? [] : noticeLines(out, agentStats, instructions);
  if (changes.length || notices.length) {
    console.log(['nexus-link:', ...changes, ...notices].join('\n  '));
  } else if (!quiet) {
    console.log(tools.length ? 'nexus-link: everything already in sync.' : 'nexus-link: no tools are set up ("tools" is empty); nothing to do.');
  }
  return 0;
}

if (require.main === module) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (err) {
    console.error(`nexus-link: ${err.message}`);
    process.exitCode = 1;
  }
}

module.exports = { main, renderCodex, renderGemini };
